defaultGroups:
    - name: users
      must_exist: true
      system: true
    - lp
    - video
    - network
    - storage
    - name: wheel
      must_exist: false
      system: true
    - audio

autologinGroup:  autologin
doAutologin:     true

sudoersGroup:    wheel
sudoersConfigureWithGroup: true

setRootPassword: true

doReusePassword: true

allowWeakPasswords: false
allowWeakPasswordsDefault: true

user:
  shell: /bin/bash
  forbidden_names: [ root ]

hostname:
  location: EtcFile
  writeHostsFile: true
  forbidden_names: [ localhost ]

presets:
    fullName:
        editable: true
    loginName:
        editable: true
