efiSystemPartition:     "/boot/efi"

userSwapChoices:
    - none
    - small
    - suspend
    - file

drawNestedPartitions:   false

alwaysShowPartitionLabels: true

initialPartitioningChoice: none

initialSwapChoice: none

defaultFileSystemType:  "ext4"

availableFileSystemTypes:  ["ext4","ext3","btrfs","jfs","xfs","f2fs"]

lvm:
    enable: false
