# Configuration file for Calamares

modules-search: [ local ]

instances:
- id:       cleanup
  module:   shellprocess
  config:   shellprocess-cleanup.conf
- id:       bootmnt
  module:   shellprocess
  config:   shellprocess-bootmnt.conf
- id:       dearchiso
  module:   shellprocess
  config:   shellprocess-dearchiso.conf

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - users
  - summary
- exec:
  - partition
  - mount
  - shellprocess@bootmnt
  - unpackfs
  - shellprocess@dearchiso
  - machineid
  - fstab
  - locale
  - keyboard
  - localecfg
  - luksbootkeyfile
  - luksopenswaphookcfg
  - initcpiocfg
  - initcpio
  - users
  - displaymanager
  - networkcfg
  - hwclock
  - services-systemd
  - grubcfg
  - bootloader
  - shellprocess@cleanup
  - preservefiles
  - umount
- show:
  - finished

branding: sigeonos

prompt-install: true

dont-chroot: false

oem-setup: false

disable-cancel: false

disable-cancel-during-exec: false

hide-back-and-next-during-exec: false

quit-at-end: false
